In [7]:
from google.colab import drive #importa o "conecta" con mi unidad de Drive
drive.mount('/content/drive')

import pandas as pd
#Importa la librería para manipulación de datos y lo asigna a "pd" para practicidad

nba = pd.read_excel('/content/drive/MyDrive/dataAnalysis/Nba Teams.xlsx')
#Es necesario cambiar el método "_csv" a "_excel" ya que el documento del que sale la información está en dicho formato

nba

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

,Name,Team,Division,Position,Height,Weight,Birth_Date,College,Salary,Country
0,Bogdan Bogdanovic,Atlanta Hawks,SouthEast,G,6'6,220.0,1992-08-18,NaN,18000000.0,RS
1,Brandon Goodwin,Atlanta Hawks,SouthEast,G,NaN,180.0,1995-10-02,Central Florida,1701593.0,US
2,Bruno Fernando,Atlanta Hawks,SouthEast,F,6'9,240.0,1998-08-15,Maryland,1517981.0,AO
3,Cam Reddish,Atlanta Hawks,SouthEast,F,6'8,218.0,1999-09-01,Duke,NaN,US
4,Clint Capela,Atlanta Hawks,SouthEast,C,6'10,240.0,1994-05-18,NaN,16000000.0,CH
...,...,...,...,...,...,...,...,...,...,...
493,Rui Hachimura,Washington Wizards,SouthEast,F,6'8,230.0,1998-02-08,Gonzaga,4692840.0,JP
494,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN
495,Russell Westbrook,Washington Wizards,SouthEast,G,6'3,200.0,1988-11-12,UCLA,41358814.0,US
496,Thomas Bryant,Washington Wizards,SouthEast,C,6'10,248.0,1997-07-31,Indiana,8333333.0,US
497,Troy Brown Jr.,Washington Wizards,SouthEast,G-F,6'6,215.0,1999-07-28,Oregon,3372840.0,US

In [9]:
nba.info()
"""
Imprime el rango de índices, desde dónde cuenta hasta dónde y cantidad de columnas
#Los tipos de datos de cada fila y un conteo final de los tipos de datos
La memoria usada
"""

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 498 entries, 0 to 497
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        484 non-null    object
 1   Team        484 non-null    object
 2   Division    484 non-null    object
 3   Position    484 non-null    object
 4   Height      470 non-null    object
 5   Weight      484 non-null    float64
 6   Birth_Date  484 non-null    datetime64[ns]
 7   College     422 non-null    object
 8   Salary      434 non-null    float64
 9   Country     484 non-null    object
dtypes: datetime64[ns](1), float64(2), object(7)
memory usage: 39.0+ KB

In [10]:
nba.head()
#Imprime las primeras 5 líneas de la información

,Name,Team,Division,Position,Height,Weight,Birth_Date,College,Salary,Country
0,Bogdan Bogdanovic,Atlanta Hawks,SouthEast,G,6'6,220.0,1992-08-18,NaN,18000000.0,RS
1,Brandon Goodwin,Atlanta Hawks,SouthEast,G,NaN,180.0,1995-10-02,Central Florida,1701593.0,US
2,Bruno Fernando,Atlanta Hawks,SouthEast,F,6'9,240.0,1998-08-15,Maryland,1517981.0,AO
3,Cam Reddish,Atlanta Hawks,SouthEast,F,6'8,218.0,1999-09-01,Duke,NaN,US
4,Clint Capela,Atlanta Hawks,SouthEast,C,6'10,240.0,1994-05-18,NaN,16000000.0,CH

In [11]:
nba.head(5).info()
#Se puede decir de cuántas filas se quiere imprimir la información

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        5 non-null      object
 1   Team        5 non-null      object
 2   Division    5 non-null      object
 3   Position    5 non-null      object
 4   Height      4 non-null      object
 5   Weight      5 non-null      float64
 6   Birth_Date  5 non-null      datetime64[ns]
 7   College     3 non-null      object
 8   Salary      4 non-null      float64
 9   Country     5 non-null      object
dtypes: datetime64[ns](1), float64(2), object(7)
memory usage: 532.0+ bytes