In [1]:
from google.colab import drive #importa o "conecta" con mi unidad de Drive
drive.mount('/content/drive')

import pandas as pd
nba = pd.read_excel('/content/drive/MyDrive/dataAnalysis/Nba Teams.xlsx')

nba.head()
#Imprime las primeras 5 filas del contenido

Mounted at /content/drive

,Name,Team,Division,Position,Height,Weight,Birth_Date,College,Salary,Country
0,Bogdan Bogdanovic,Atlanta Hawks,SouthEast,G,6'6,220.0,1992-08-18,NaN,18000000.0,RS
1,Brandon Goodwin,Atlanta Hawks,SouthEast,G,NaN,180.0,1995-10-02,Central Florida,1701593.0,US
2,Bruno Fernando,Atlanta Hawks,SouthEast,F,6'9,240.0,1998-08-15,Maryland,1517981.0,AO
3,Cam Reddish,Atlanta Hawks,SouthEast,F,6'8,218.0,1999-09-01,Duke,NaN,US
4,Clint Capela,Atlanta Hawks,SouthEast,C,6'10,240.0,1994-05-18,NaN,16000000.0,CH

In [2]:
nba.sort_values("Name").head(20)
#Ordena el contenido por orden alfabético ya que asume la columna "Name" como índice e imprime las primeras 20 filas

,Name,Team,Division,Position,Height,Weight,Birth_Date,College,Salary,Country
354,Aaron Gordon,Orlando Magic,SouthEast,F,6'8,235.0,1995-09-16,Arizona,18136364.0,US
186,Aaron Holiday,Indiana Pacers,Central,G,NaN,185.0,1996-09-30,UCLA,2345640.0,US
18,Aaron Nesmith,Boston Celtics,Atlantic,G-F,6'6,213.0,1999-10-16,Vanderbilt,3458400.0,US
388,Abdel Nader,Phoenix Suns,Pacific,F,6'5,225.0,1993-09-25,"Northern Illinois, Iowa State",1752950.0,EG
70,Adam Mokoka,Chicago Bulls,Central,G,6'5,190.0,1998-07-18,NaN,NaN,FR
337,Al Horford,Oklahoma City Thunder,NorthWest,C-F,6'9,240.0,1986-06-03,Florida,27500000.0,DO
355,Al-Farouq Aminu,Orlando Magic,SouthEast,F,6'8,220.0,1990-09-21,Wake Forest,9720900.0,US
319,Alec Burks,New York Knicks,Atlantic,G,6'6,214.0,1991-07-20,Colorado,6000000.0,US
338,Aleksej Pokusevski,Oklahoma City Thunder,NorthWest,F,6'11,215.0,2001-12-26,NaN,2964840.0,RS
219,Alex Caruso,Los Angeles Lakers,Pacific,G,6'5,186.0,1994-02-28,Texas A&M,2750000.0,US
449,Alex Len,Toronto Raptors,Atlantic,C,7'0,250.0,1993-06-16,Maryland,2320000.0,UA
220,Alfonzo McKinnie,Los Angeles Lakers,Pacific,F,6'7,215.0,1992-09-17,Green Bay,1762796.0,US
85,Andre Drummond,Cleveland Cavaliers,Central,C,6'10,279.0,1993-08-10,UConn,28751775.0,US
251,Andre Iguodala,Miami Heat,SouthEast,G-F,6'6,215.0,1984-01-28,Arizona,15000000.0,US
153,Andrew Wiggins,Golden State Warriors,Pacific,F-G,6'7,197.0,1995-02-23,Kansas,29542010.0,CA
403,Anfernee Simons,Portland Trail Blazers,NorthWest,G,6'3,181.0,1999-06-08,NaN,2252040.0,US
221,Anthony Davis,Los Angeles Lakers,Pacific,F-C,6'10,253.0,1993-03-11,Kentucky,32742000.0,US
286,Anthony Edwards,Minnesota Timberwolves,NorthWest,G,6'5,225.0,2001-08-05,Georgia,9757440.0,US
481,Anthony Gill,Washington Wizards,SouthEast,F,6'8,230.0,1992-10-17,"South Carolina, Virginia",898310.0,US
450,Aron Baynes,Toronto Raptors,Atlantic,C,6'10,260.0,1986-12-09,Washington State,6975610.0,NZ

In [21]:
#nba.sort_values("Salary")
  #Ordena los valores contenidos en "Salary"

import pandas as pd
nba = pd.read_excel('/content/drive/MyDrive/dataAnalysis/Nba Teams.xlsx')
nba.dropna(inplace=True)
  #Elimina llos valores nulos dentro del contenido
#nba

nba = nba.sort_values("Salary", ascending = True)
  #Ordena los valores contenidos en "Salary"
nba

,Name,Team,Division,Position,Height,Weight,Birth_Date,College,Salary,Country
248,Sean McDermott,Memphis Grizzlies,SouthWest,F,6'6,195.0,1996-11-03,Butler,280000.0,US
254,Breein Tyree,Miami Heat,SouthEast,G,6'2,195.0,1998-01-13,Ole Miss,280000.0,US
225,Kostas Antetokounmpo,Los Angeles Lakers,Pacific,F,6'10,200.0,1997-11-20,Dayton,280000.0,GR
245,Killian Tillie,Memphis Grizzlies,SouthWest,F,6'10,220.0,1998-03-05,Gonzaga,380000.0,FR
350,Omer Yurtseven,Oklahoma City Thunder,NorthWest,C,7'0,264.0,1998-06-19,"NC State, Georgetown",485000.0,TR
...,...,...,...,...,...,...,...,...,...,...
180,James Harden,Houston Rockets,SouthWest,G,6'5,220.0,1989-08-26,Arizona State,40824000.0,US
181,John Wall,Houston Rockets,SouthWest,G,6'4,210.0,1990-09-06,Kentucky,41254920.0,US
495,Russell Westbrook,Washington Wizards,SouthEast,G,6'3,200.0,1988-11-12,UCLA,41358814.0,US
391,Chris Paul,Phoenix Suns,Pacific,G,6'1,175.0,1985-05-06,Wake Forest,41358814.0,US
168,Stephen Curry,Golden State Warriors,Pacific,G,6'3,185.0,1988-03-14,Davidson,43006362.0,US

In [23]:
#nba.sort_values(["Team", "Name"])
  #Ordena los valores contenidos en "Team" y "Name"
nba.sort_values(["Team", "Name"], na_position = 'first')
  #Coloca los valores nulos al principio del contenido, sin embargo como en el código anterior se eliminaron los valores nulos no se ve

,Name,Team,Division,Position,Height,Weight,Birth_Date,College,Salary,Country
2,Bruno Fernando,Atlanta Hawks,SouthEast,F,6'9,240.0,1998-08-15,Maryland,1517981.0,AO
6,De'Andre Hunter,Atlanta Hawks,SouthEast,F,6'7,225.0,1997-12-02,Virginia,7422000.0,US
7,John Collins,Atlanta Hawks,SouthEast,F,6'9,235.0,1997-09-23,Wake Forest,4137302.0,US
8,Kevin Huerter,Atlanta Hawks,SouthEast,G,6'7,190.0,1998-08-27,Maryland,2761920.0,US
10,Kris Dunn,Atlanta Hawks,SouthEast,G,6'3,205.0,1994-03-18,Providence,4767000.0,US
...,...,...,...,...,...,...,...,...,...,...
492,Robin Lopez,Washington Wizards,SouthEast,C,7'0,281.0,1988-04-01,Stanford,7300000.0,US
493,Rui Hachimura,Washington Wizards,SouthEast,F,6'8,230.0,1998-02-08,Gonzaga,4692840.0,JP
495,Russell Westbrook,Washington Wizards,SouthEast,G,6'3,200.0,1988-11-12,UCLA,41358814.0,US
496,Thomas Bryant,Washington Wizards,SouthEast,C,6'10,248.0,1997-07-31,Indiana,8333333.0,US
497,Troy Brown Jr.,Washington Wizards,SouthEast,G-F,6'6,215.0,1999-07-28,Oregon,3372840.0,US