In [ ]:
from google.colab import drive #importa o "conecta" con mi unidad de Drive
drive.mount('/content/drive')

import pandas as pd
nba = pd.read_excel('/content/drive/MyDrive/dataAnalysis/Nba Teams.xlsx')

Mounted at /content/drive

In [ ]:
nba.head(10)
#Imprime las primeras 10 filas del contenido

,Name,Team,Division,Position,Height,Weight,Birth_Date,College,Salary,Country
0,Bogdan Bogdanovic,Atlanta Hawks,SouthEast,G,6'6,220.0,1992-08-18,NaN,18000000.0,RS
1,Brandon Goodwin,Atlanta Hawks,SouthEast,G,NaN,180.0,1995-10-02,Central Florida,1701593.0,US
2,Bruno Fernando,Atlanta Hawks,SouthEast,F,6'9,240.0,1998-08-15,Maryland,1517981.0,AO
3,Cam Reddish,Atlanta Hawks,SouthEast,F,6'8,218.0,1999-09-01,Duke,NaN,US
4,Clint Capela,Atlanta Hawks,SouthEast,C,6'10,240.0,1994-05-18,NaN,16000000.0,CH
5,Danilo Gallinari,Atlanta Hawks,SouthEast,F,6'10,233.0,1988-08-08,NaN,19500000.0,IT
6,De'Andre Hunter,Atlanta Hawks,SouthEast,F,6'7,225.0,1997-12-02,Virginia,7422000.0,US
7,John Collins,Atlanta Hawks,SouthEast,F,6'9,235.0,1997-09-23,Wake Forest,4137302.0,US
8,Kevin Huerter,Atlanta Hawks,SouthEast,G,6'7,190.0,1998-08-27,Maryland,2761920.0,US
9,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN

In [ ]:
nba.fillna(0)
#Reemplaza todos los valores nulos por un 0

,Name,Team,Division,Position,Height,Weight,Birth_Date,College,Salary,Country
0,Bogdan Bogdanovic,Atlanta Hawks,SouthEast,G,6'6,220.0,1992-08-18 00:00:00,0,18000000.0,RS
1,Brandon Goodwin,Atlanta Hawks,SouthEast,G,0,180.0,1995-10-02 00:00:00,Central Florida,1701593.0,US
2,Bruno Fernando,Atlanta Hawks,SouthEast,F,6'9,240.0,1998-08-15 00:00:00,Maryland,1517981.0,AO
3,Cam Reddish,Atlanta Hawks,SouthEast,F,6'8,218.0,1999-09-01 00:00:00,Duke,0.0,US
4,Clint Capela,Atlanta Hawks,SouthEast,C,6'10,240.0,1994-05-18 00:00:00,0,16000000.0,CH
...,...,...,...,...,...,...,...,...,...,...
493,Rui Hachimura,Washington Wizards,SouthEast,F,6'8,230.0,1998-02-08 00:00:00,Gonzaga,4692840.0,JP
494,0,0,0,0,0,0.0,0,0,0.0,0
495,Russell Westbrook,Washington Wizards,SouthEast,G,6'3,200.0,1988-11-12 00:00:00,UCLA,41358814.0,US
496,Thomas Bryant,Washington Wizards,SouthEast,C,6'10,248.0,1997-07-31 00:00:00,Indiana,8333333.0,US
497,Troy Brown Jr.,Washington Wizards,SouthEast,G-F,6'6,215.0,1999-07-28 00:00:00,Oregon,3372840.0,US

In [ ]:
nba["College"] = nba["College"].fillna(0)
nba
#Asigna a los valores nulos de la columna "College" un 0

<ipython-input-11-6a807906c592>:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  nba["College"] = nba["College"].fillna(0)

,Name,Team,Division,Position,Height,Weight,Birth_Date,College,Salary,Country
0,Bogdan Bogdanovic,Atlanta Hawks,SouthEast,G,6'6,220.0,1992-08-18,0,18000000.0,RS
1,Brandon Goodwin,Atlanta Hawks,SouthEast,G,NaN,180.0,1995-10-02,0,1701593.0,US
2,Bruno Fernando,Atlanta Hawks,SouthEast,F,6'9,240.0,1998-08-15,0,1517981.0,AO
3,Cam Reddish,Atlanta Hawks,SouthEast,F,6'8,218.0,1999-09-01,0,NaN,US
4,Clint Capela,Atlanta Hawks,SouthEast,C,6'10,240.0,1994-05-18,0,16000000.0,CH
...,...,...,...,...,...,...,...,...,...,...
493,Rui Hachimura,Washington Wizards,SouthEast,F,6'8,230.0,1998-02-08,0,4692840.0,JP
494,Missing name,NaN,NaN,NaN,NaN,NaN,NaT,0,NaN,NaN
495,Russell Westbrook,Washington Wizards,SouthEast,G,6'3,200.0,1988-11-12,0,41358814.0,US
496,Thomas Bryant,Washington Wizards,SouthEast,C,6'10,248.0,1997-07-31,0,8333333.0,US
497,Troy Brown Jr.,Washington Wizards,SouthEast,G-F,6'6,215.0,1999-07-28,0,3372840.0,US

In [ ]:
nba["name"] = nba["Name"].fillna("Missing name")
nba
#Asigna a los valores nulos de "name" un nuevo valor "Missing name"

,Name,Team,Division,Position,Height,Weight,Birth_Date,College,Salary,Country,name
0,Bogdan Bogdanovic,Atlanta Hawks,SouthEast,G,6'6,220.0,1992-08-18,0,18000000.0,RS,Bogdan Bogdanovic
1,Brandon Goodwin,Atlanta Hawks,SouthEast,G,NaN,180.0,1995-10-02,0,1701593.0,US,Brandon Goodwin
2,Bruno Fernando,Atlanta Hawks,SouthEast,F,6'9,240.0,1998-08-15,0,1517981.0,AO,Bruno Fernando
3,Cam Reddish,Atlanta Hawks,SouthEast,F,6'8,218.0,1999-09-01,0,NaN,US,Cam Reddish
4,Clint Capela,Atlanta Hawks,SouthEast,C,6'10,240.0,1994-05-18,0,16000000.0,CH,Clint Capela
...,...,...,...,...,...,...,...,...,...,...,...
493,Rui Hachimura,Washington Wizards,SouthEast,F,6'8,230.0,1998-02-08,0,4692840.0,JP,Rui Hachimura
494,Missing name,NaN,NaN,NaN,NaN,NaN,NaT,0,NaN,NaN,Missing name
495,Russell Westbrook,Washington Wizards,SouthEast,G,6'3,200.0,1988-11-12,0,41358814.0,US,Russell Westbrook
496,Thomas Bryant,Washington Wizards,SouthEast,C,6'10,248.0,1997-07-31,0,8333333.0,US,Thomas Bryant
497,Troy Brown Jr.,Washington Wizards,SouthEast,G-F,6'6,215.0,1999-07-28,0,3372840.0,US,Troy Brown Jr.