In [4]:
from google.colab import drive #importa o "conecta" con mi unidad de Drive
drive.mount('/content/drive')

import pandas as pd
nba = pd.read_excel('/content/drive/MyDrive/dataAnalysis/Nba Teams.xlsx')
nba.tail()
  #Imprime las últimas 5 líneas de información
#nba

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

,Name,Team,Division,Position,Height,Weight,Birth_Date,College,Salary,Country
493,Rui Hachimura,Washington Wizards,SouthEast,F,6'8,230.0,1998-02-08,Gonzaga,4692840.0,JP
494,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN
495,Russell Westbrook,Washington Wizards,SouthEast,G,6'3,200.0,1988-11-12,UCLA,41358814.0,US
496,Thomas Bryant,Washington Wizards,SouthEast,C,6'10,248.0,1997-07-31,Indiana,8333333.0,US
497,Troy Brown Jr.,Washington Wizards,SouthEast,G-F,6'6,215.0,1999-07-28,Oregon,3372840.0,US

In [5]:
from google.colab import drive
drive.mount('/content/drive')
#conecta con mi contenido de drive

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [6]:
nba.info()
#imprime el rango de índices y las columnas (las dimensiones)
#El tipo de dato de cada columna con su conteo final
#Uso de memoria

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 498 entries, 0 to 497
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        484 non-null    object
 1   Team        484 non-null    object
 2   Division    484 non-null    object
 3   Position    484 non-null    object
 4   Height      470 non-null    object
 5   Weight      484 non-null    float64
 6   Birth_Date  484 non-null    datetime64[ns]
 7   College     422 non-null    object
 8   Salary      434 non-null    float64
 9   Country     484 non-null    object
dtypes: datetime64[ns](1), float64(2), object(7)
memory usage: 39.0+ KB

In [7]:
nba.isnull()
#Imprime la información con booleanos si algún contenido es nulo o vacío

,Name,Team,Division,Position,Height,Weight,Birth_Date,College,Salary,Country
0,False,False,False,False,False,False,False,True,False,False
1,False,False,False,False,True,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,True,False
4,False,False,False,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...
493,False,False,False,False,False,False,False,False,False,False
494,True,True,True,True,True,True,True,True,True,True
495,False,False,False,False,False,False,False,False,False,False
496,False,False,False,False,False,False,False,False,False,False
497,False,False,False,False,False,False,False,False,False,False

In [8]:
nba.isnull().sum()
#Cuenta cuántos elementos nulos hay en cada columna

Name          14
Team          14
Division      14
Position      14
Height        28
Weight        14
Birth_Date    14
College       76
Salary        64
Country       14
dtype: int64